---
title: "Penalties_byTeam_byReferee"
output: html_document
latex_engine: xelatex

---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cluster)
library(ggplot2)
library(dplyr)
library(lubridate)
library(stringr)
setwd(getwd())

dataFile<-'./data/df_ref.csv'

refData<-read_csv(dataFile)
#summarize(refData)
```



```{r}
#NOW WE LOOK BY REFEREE
penRef<-refData %>%
  group_by(Referee) %>%
  summarize(n=n())

colnames(penRef)<-c("Referee","n")

refDataTemp<-refData
refDataTemp$UniqueRef<-paste(refDataTemp$GameDate,refDataTemp$Referee)

gameRef<-refDataTemp %>%
  group_by(UniqueRef) %>%
  summarize(n=n())

#gameRef

tempVar <-str_split_fixed(gameRef$UniqueRef,' ',2)
#tempVar[,2]

gameRef$UniqueRef<-tempVar[,2]
colnames(gameRef)<-c("Referee","NumGames")

gameRef<-gameRef %>%
  group_by(Referee) %>%
  summarize(n=n())
gameRef
colnames(gameRef)<-c("Referee","NumGames")

penRef<-merge(x=penRef,y=gameRef, by='Referee')
penRef$PenPerGame <- penRef$n/penRef$NumGames

#ggplot(penRef, aes(x=reorder(Referee,n),y=n))+geom_col()+coord_flip()+ggtitle("Number of Penalties Given by Referee")+xlab('Ref Name')+ylab('No. of Penalties')+theme_bw()
#ggplot(penRef, aes(x=reorder(Referee,n),y=PenPerGame))+geom_col()+coord_flip()+ggtitle("Number of Penalties Given by Referee Per Game")+xlab('Ref Name')+ylab('No. of Penalties')+theme_bw()
ggplot(penRef, aes(x=reorder(Referee,PenPerGame),y=PenPerGame))+geom_point()+coord_flip()+ggtitle("Number of Penalties Given by Referee Per Game")+xlab('Ref Name')+ylab('No. of Penalties / Game')+theme_bw()+geom_hline(yintercept=(mean(penRef$PenPerGame)),color='Red',alpha=0.4)
summary(penRef$PenPerGame)


```