---
title: "Untitled"
author: "Connor Daly - ctd2121"
date: "12/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv('./data/df_ref.csv')

library(ggplot2)
library(dplyr)
library(tidyr)
# Ignore penalties called in overtime (denoted by quarter 5)
df1 <- df %>%
  filter(Quarter < 5)

df_by_q <- df1[c(1,5,6,2)]
df_by_q <- df_by_q %>%
  filter(Quarter < 5) %>%
  mutate(gameID = paste(GameDate, OffenseTeam, DefenseTeam))
len <- n_distinct(df_by_q$gameID)
df_by_q$Quarter <- as.factor(df_by_q$Quarter)
df_by_q <- df_by_q %>%
  group_by(Quarter) %>%
  summarise(count = n()) %>%
  mutate(count = count/len)

ggplot(df_by_q, aes(x = Quarter, y = count, width = 0.8)) +
  geom_bar(stat = "identity", color = "black", fill = "red", alpha = 0.6) +
  ggtitle("Penalties per Game by Quarter") +
  xlab("Quarter") +
  ylab("Count Per Game") +
  theme(axis.title.x = element_text(size = 16),
       axis.title.y = element_text(size = 16),
       plot.title = element_text(hjust = 0.5, size = 18))
```

```{r}
# Same as above, but now including overtime
# Ignore penalties called in overtime (denoted by quarter 5)
df2 <- df

df_by_q <- df2[c(1,5,6,2)]
df_by_q <- df_by_q %>%
  mutate(gameID = paste(GameDate, OffenseTeam, DefenseTeam))
reg_len <- n_distinct(df_by_q$gameID)
ot <- df_by_q %>%
  filter(Quarter == 5)
ot_len <- n_distinct(ot$gameID)
df_by_q <- df_by_q %>%
  group_by(Quarter) %>%
  summarise(count = n()) %>%
  mutate(adj_count = ifelse(Quarter < 5, count/reg_len, count/ot_len))
df_by_q$Quarter <- as.factor(df_by_q$Quarter)
levels(df_by_q$Quarter) <- c("Q1", "Q2", "Q3", "Q4", "Overtime")


ggplot(df_by_q, aes(x = Quarter, y = adj_count, width = 0.8)) +
  geom_bar(stat = "identity", color = "black", fill = "red", alpha = 0.6) +
  ggtitle("Penalties per Game by Quarter") +
  xlab("Quarter") +
  ylab("Count Per Game") +
  theme(axis.title.x = element_text(size = 16),
       axis.title.y = element_text(size = 16),
       plot.title = element_text(hjust = 0.5, size = 18))
```