---
title: "PenaltyTypeAnalysis"
author: "ThompsonBliss"
date: "November 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

```

## Do Referee Crews call each penalty type at the same frequency?



```{r fig.height = 6}

#Putting Together Data
library(dplyr)
library(ggplot2)

df_ref <- read.csv('./data/df_ref.csv')

#Calculating Average ref data
totalNumberOfGames = nlevels(as.factor(paste(df_ref$GameDate, df_ref$Home)))

#Calculating number of games each ref worked
totalNumberOfGamesByRef <- unique(df_ref[c("Referee", "GameDate")]) %>% group_by(Referee) %>% summarize(numReffed = n())


#Adding the total game numbers to the df_ref
df_ref = merge(df_ref, totalNumberOfGamesByRef, by = "Referee")


#Getting average penalty types called for all refs
averagePenaltyTypeCalled = table(df_ref$PenaltyType) / totalNumberOfGames

#Getting Average called by refs
PenTypeCounts <- df_ref %>% group_by(Referee, PenaltyType) %>% 
    summarize(Freq = n() / numReffed[1])

#Removing NA/Other Categories
PenTypeCounts <- PenTypeCounts[!is.na(PenTypeCounts$Referee),]
PenTypeCounts <- PenTypeCounts[PenTypeCounts$PenaltyType != "OTHER",]

#Changing Data sorted by ref to diversion from average of all refs
for (penType in levels(df_ref$PenaltyType)){
  PenTypeCounts[PenTypeCounts$PenaltyType == penType,]$Freq = 
 1  - PenTypeCounts[PenTypeCounts$PenaltyType == penType,]$Freq/as.double(averagePenaltyTypeCalled[penType])
}

ggplot(as.data.frame(averagePenaltyTypeCalled), aes(x = reorder(Var1, - Freq), y = Freq)) + geom_bar(stat = "identity") + theme(plot.title = element_text(hjust = 0.5), axis.text.x  = element_text(angle=45, hjust = 1)) + xlab("Penalty Type") + ylab("Average Number called per Game") + ggtitle("Average Number of Each Penalty Type Called Per Game")

```

```{r fig.width = 8, fig.height = 14}
#Setting Color Scheme
PenTypeCounts$FreqType = PenTypeCounts$Freq < 0

#Plotting Data Faceted by Ref
ggplot(PenTypeCounts, aes(x=PenaltyType, y=Freq, fill=FreqType))+
  geom_bar(stat="identity",position="identity")+ ggtitle("Percentage of Increase/Decrease from Average Penalty Type Called") + xlab("Penalty Type") + ylab("Percentage of Divergence from Average") + scale_fill_manual(values = c("green","red"), guide = FALSE)+ facet_wrap(~Referee, nrow = 8, ncol = 2, scales = 'free_x') + coord_flip() + ylim(-0.6, 0.6) + geom_hline(yintercept=0) + theme(panel.spacing = unit(1, "lines"))

```
